// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ApplyAndSaveConfig(arg1) {
  return window['go']['app']['App']['ApplyAndSaveConfig'](arg1);
}

export function ApplyConfig(arg1) {
  return window['go']['app']['App']['ApplyConfig'](arg1);
}

export function CodeSummarize(arg1) {
  return window['go']['app']['App']['CodeSummarize'](arg1);
}

export function GetConfig() {
  return window['go']['app']['App']['GetConfig']();
}

export function GetFileContent(arg1) {
  return window['go']['app']['App']['GetFileContent'](arg1);
}

export function GetReportList() {
  return window['go']['app']['App']['GetReportList']();
}

export function LoadAndApplyConfig() {
  return window['go']['app']['App']['LoadAndApplyConfig']();
}

export function LoadConfig() {
  return window['go']['app']['App']['LoadConfig']();
}

export function PushMessage(arg1) {
  return window['go']['app']['App']['PushMessage'](arg1);
}

export function SaveConfig(arg1) {
  return window['go']['app']['App']['SaveConfig'](arg1);
}

export function SelectFolder() {
  return window['go']['app']['App']['SelectFolder']();
}

export function Stop() {
  return window['go']['app']['App']['Stop']();
}

export function StreamAnswer(arg1) {
  return window['go']['app']['App']['StreamAnswer'](arg1);
}
