// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {cfgs} from '../models';
import {openai} from '../models';

export function ApplyAndSaveConfig(arg1:cfgs.Config):Promise<void>;

export function ApplyConfig(arg1:cfgs.Config):Promise<void>;

export function CodeSummarize(arg1:string):Promise<string>;

export function GetConfig():Promise<cfgs.Config>;

export function GetFileContent(arg1:string):Promise<string>;

export function GetReportList():Promise<Array<string>>;

export function LoadAndApplyConfig():Promise<cfgs.Config>;

export function LoadConfig():Promise<cfgs.Config>;

export function PushMessage(arg1:openai.ChatCompletionMessage):Promise<void>;

export function SaveConfig(arg1:cfgs.Config):Promise<void>;

export function SelectFolder():Promise<string>;

export function Stop():Promise<void>;

export function StreamAnswer(arg1:string):Promise<void>;
